### ISSUE TITLE
prometheus v1 is out

### ISSUE THREAD

**Issue by pjfanning** [varwise/prometheus-pekko-http#5]
APIs are similar but have changed - compared to simpleclient 0.16.

This is an example where I changed over to the new prometheus APIs.
https://github.com/pjfanning/micrometer-pekko-sample/commit/f850badcd9c0818923bdcd4466f7487813cbdf4e

**Comment by wlk** [comment]
Thanks for the report this will be updated in https://github.com/varwise/prometheus-pekko-http/pull/6

**Comment by wlk** [comment]
2.0.0 of prometheus-pekko-http was released
